spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db/example.db
    username:
    password:
  ### sqlite需要自己配置连接方式
  jpa:
    database-platform: com.example.util.SQLiteDialect #自己配置的方言
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
